steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["backend", "deploy"]
    dir: backend
    timeout: "1600s"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["frontend", "deploy"]
    dir: backend
    timeout: "1600s"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["dispatch", "deploy"]
    timeout: "30s"
